version: "3"

services:
  influxdb:
    image: 'influxdb'
    ports:
      - "8086:8086"
    volumes:
      - './tmp/influxdb:/var/lib/influxdb'
  grafana:
    image: 'grafana/grafana'
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_DEFAULT_INSTANCE_NAME: iotalis-grafana
    volumes:
      - './tmp/grafana:/var/lib/grafana'