version: "2"

services:
  influxdb:
    image: 'influxdb:alpine'
    ports:
      - "8086:8086"
    volumes:
      - './tmp/influxdb:/var/lib/influxdb'
    environment:
      PRE_CREATE_DB: iotalis
  grafana:
    image: 'grafana/grafana'
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_DEFAULT_INSTANCE_NAME: iotalis-grafana
      GF_USERS_ALLOW_SIGNUP: "false"
    volumes:
      - './tmp/grafana:/var/lib/grafana'